//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hotel.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(EmployeeVM))]
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.AttendanceAndLeaves = new HashSet<AttendanceAndLeave>();
        }

        public int id { get; set; }
        public string name { get; set; }
        public string ssn { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        public string period_of_work { get; set; }
        public string type_of_work { get; set; }
        public Nullable<decimal> salary { get; set; }
        public byte[] fingerprint { get; set; }
        public Nullable<System.DateTime> start_of_work { get; set; }
        public Nullable<System.DateTime> end_of_work { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttendanceAndLeave> AttendanceAndLeaves { get; set; }
    }
    public class EmployeeVM
    {
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> start_of_work { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> end_of_work { get; set; }
    }
}