//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<decimal> cost { get; set; }
        public Nullable<int> res_id { get; set; }
    
        public virtual Reservation Reservation { get; set; }
    }
}
